name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixar o código do repositório
        uses: actions/checkout@v4

      - name: 2. Configurar o Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: 3. Compilar o projeto
        run: ./mvnw clean package -DskipTests

      - name: 4. Fazer Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 5. Build e Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/main/docker/Dockerfile.jvm
          push: true
          tags: |
            ryanocastro/quarkus-app:v${{ github.run_number }}
            ryanocastro/quarkus-app:latest