{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "system_cpu_usage{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{pod=~\"$pod\"}",
     "legendFormat": "{{pod}} system-1m"
    },
    {
     "expr": "system_cpu_count{pod=~\"$pod\"}",
     "legendFormat": "{{pod}} cpus"
    }
   ]
  },
  { "title": "Memória", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_used_bytes{pod=~\"$pod\", area=\"heap\"})",
     "legendFormat": "{{pod}} used"
    },
    {
     "expr": "sum by (pod) (jvm_memory_committed_bytes{pod=~\"$pod\", area=\"heap\"})",
     "legendFormat": "{{pod}} committed"
    },
    {
     "expr": "sum by (pod) (jvm_memory_max_bytes{pod=~\"$pod\", area=\"heap\"})",
     "legendFormat": "{{pod}} max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_used_bytes{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (jvm_memory_committed_bytes{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP EndPoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{pod=~\"$pod\"}[2m])",
     "legendFormat": "{{pod}} - {{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Media de tempo requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{pod=~\"$pod\"}[4m]) / rate(http_server_requests_seconds_count{pod=~\"$pod\"}[4m])",
     "legendFormat": "{{pod}} - {{method}} - {{uri}} - {{status}}"
    }
   ]
  }
 ]
}